import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import NavBar from "./components/navbar/navbar";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "./globals.css";


const cinzel = Cinzel({
  subsets:["latin"],
  weight:"500"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cinzel.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
